### ISSUE TITLE
为啥没有DOUAudioVisualizer

### ISSUE THREAD

**Issue by Veryed-VS** [LavareX/DoubanFM#2]
DOUAudioVisualizer  找不到？

**Comment by LavareX** [comment]
第三方库都是用`CocoaPods`进行配置的，当时忘记把`CocoaPods`的配置信息上传到`Github`。
你可以在这里找到 [DOUAudioVisualizer](https://github.com/douban/DOUAudioStreamer/blob/master/src/DOUAudioVisualizer.h)。
